name: Run WhatsApp Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Start Bot & Keep Alive
        run: |
          node index.js &
          sleep 14000

      - name: Auto-Save Session
        continue-on-error: true
        run: |
          git config --global user.name "Session Bot"
          git config --global user.email "bot@github.com"
          git add session/
          git commit -m "Auto save session state [skip ci]" || echo "No changes"
          git push
          
